name: flutter_starter_kit
description: "Application BDD directement accessible."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get_it: ^7.2.0
  injectable: ^2.4.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  flavor: ^2.0.0
  intl: ^0.19.0
  dio_mocked_responses: ^1.4.0
  flutter_svg: ^2.0.10+1
  characters: ^1.3.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  hive: ^2.2.3
  freezed_annotation: ^2.4.4
  transparent_image: ^2.0.1
  go_router: ^14.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  flutter_flavorizr: ^2.2.3
  bdd_widget_test: ^1.7.4
  freezed: ^2.5.7
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
